version: '3.9'
services:
  # mongdb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: docker-root
  #     MONGO_INITDB_ROOT_PASSWORD: docker-pwd

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker-pass
      # POSTGRES_USER: docker-user
      # POSTGRES_DB: chat_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass  docker-pass
    ports:
      - '6379:6379'
  

#   api:
#     container_name: quotes-api
#     build:
#       context: ./
#       target: production
#     image: quotes-api
#     depends_on:
#       - db
#       - cache
#     ports:
#       - 3000:3000
#     environment:
#       NODE_ENV: production
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       DB_NAME: postgres
#       REDIS_HOST: cache
#       REDIS_PORT: 6379
#       REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     links:
#       - db
#       - cache
#     volumes:
#       - ./:/src
# volumes:
#   db:
#     driver: local
#   cache:
#     driver: local