version: '3.9'
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker-pass
      POSTGRES_USER: docker-user
      POSTGRES_DB: chat_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass  docker-pass
    ports:
      - '6379:6379'
  